name: Build and Deploy Flying Plate App to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Backend Setup
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      
      - name: Build Backend (Skip if not needed)
        run: |
          cd backend
          npm run build || echo "No build step for backend"

      # Frontend Setup
      - name: Install Frontend Dependencies
        run: |
          cd frontend/recipe-share-app
          npm install

      - name: Build Frontend
        run: |
          cd frontend/recipe-share-app
          npm run build

      # Archive backend
      - name: Archive Backend for Deployment
        run: |
          cd backend
          zip -r ../backend.zip . -x "node_modules/*"

      # Archive frontend
      - name: Archive Frontend for Deployment
        run: |
          cd frontend/recipe-share-app/dist
          zip -r ../../frontend.zip .

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend.zip

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-backend.outputs.webapp-url }}

    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend

      - name: Unzip Backend
        run: unzip backend.zip -d backend

      - name: Unzip Frontend
        run: unzip frontend.zip -d frontend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy Backend to Azure
        id: deploy-backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RecipeApp'
          slot-name: 'Production'
          package: backend

      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RecipeApp'
          slot-name: 'Production'
          package: frontend

      - name: Debug Deployment
        run: ls -R /home/site/wwwroot/
