name: Build and Deploy Node.js App to Azure Web App - RecipeApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend/recipe-share-app
        run: npm install

      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # Build frontend
      - name: Build frontend
        working-directory: frontend/recipe-share-app
        run: |
          npm run build

      # Copy frontend build to backend (so backend can serve frontend)
      - name: Serve frontend from backend
        run: |
          cp -r frontend/recipe-share-app/dist backend/build

      # Build backend (if needed, otherwise skip)
      - name: Build backend
        working-directory: backend
        run: npm run build || echo "No build step for backend"

      # Compress backend for deployment
      - name: Compress backend for deployment
        working-directory: backend
        run: zip -r ../backend-app.zip .

      # Upload artifact for deployment
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: deployment_package

      #  **Login to Azure** (Required for deployment)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E0603940A7640E49372B8E3CE9D3C89 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B2241093D674B73B37A6C0B311ECD1D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB9224BF3DA743278BA2F47E552830AB }}

      # Deploy Backend to Azure Web App
      - name: Deploy Backend to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RecipeApp'
          slot-name: 'Production'
          package: ./deployment_package/backend-app.zip
        env:
          NODE_ENV: production
