# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - RecipeApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Debug:List files
        run: ls -R

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Build backend (if applicable)
        run: |
          cd backend
          npm run build || echo "No build step for backend"

      # Frontend setup
      - name: Install frontend dependencies
        run: |
          cd frontend/recipe-share-app
          npm install

      - name: Build frontend
        run: |
          cd frontend/recipe-share-app
          npm run build 
      # - name: npm install, build, and test
      #   run: |
      #     npm install
      #     npm run build --if-present
      #     npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Debug:List extracted files
        run: ls -R

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Debug Azure Secrets
        run: |
          echo "Client ID: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID }}"
          echo "Subscription ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B63D9A4BF56B452886AA42CAA2BBF9DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_171C5DE7DB61435395FD2FF5B3C8DD2B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3EC6B2CE1A6246F389F5C86C0533CD70 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RecipeApp'
          slot-name: 'Production'
          package: backend
          # package: .

      - name: Deploy Frontend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AIAgentCICDPipeline'
          slot-name: 'Production'
          package: frontend/recipe-share-app/dist

      - name: Start Backend Server
        run: |
          cd backend
          npm start &
      
      - name: Start Frontend Server
        run: |
          cd frontend/recipe-share-app
          npm start &   
          
