name: Build and deploy Node.js app to Azure Web App - RecipeApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
    
      # Backend setup
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Frontend setup
      - name: Install frontend dependencies
        run: |
          cd frontend/recipe-share-app
          npm install
      - name: Build frontend
        run: |
          cd frontend/recipe-share-app
          npm run build 

      # Zip and Upload Backend Artifact
      - name: Zip backend for deployment
        run: |
          cd backend
          zip -r ../backend-artifact.zip .
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend-artifact.zip

      # Zip and Upload Frontend Artifact
      - name: Zip frontend for deployment
        run: |
          cd frontend/recipe-share-app
          zip -r ../../frontend-artifact.zip dist
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: frontend-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
      - name: Unzip backend artifact
        run: |
          mkdir -p backend
          unzip backend-artifact.zip -d backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact
      - name: Unzip frontend artifact
        run: |
          mkdir -p frontend/recipe-share-app/dist
          unzip frontend-artifact.zip -d frontend/recipe-share-app/dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E0603940A7640E49372B8E3CE9D3C89 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1B2241093D674B73B37A6C0B311ECD1D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB9224BF3DA743278BA2F47E552830AB }}

      - name: Deploy Backend to Azure Web App
        id: deploy-backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RecipeApp'
          slot-name: 'Production'
          package: backend

      - name: Deploy Frontend to Azure Web App
        id: deploy-frontend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'RecipeApp'
          slot-name: 'Production'
          package: frontend/recipe-share-app/dist

      - name: Debug:List deployed files
        run: ls -R /home/site/wwwroot/
